//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.Resources.MiscResources", typeof(MiscResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acquiring data... ähnelt.
        /// </summary>
        internal static string AcquiringData {
            get {
                return ResourceManager.GetString("AcquiringData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation in Progress ähnelt.
        /// </summary>
        internal static string ActiveOperations {
            get {
                return ResourceManager.GetString("ActiveOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ({0}) ähnelt.
        /// </summary>
        internal static string AllCount {
            get {
                return ResourceManager.GetString("AllCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred when trying to authorize. ähnelt.
        /// </summary>
        internal static string AuthError {
            get {
                return ResourceManager.GetString("AuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deskewing... ähnelt.
        /// </summary>
        internal static string AutoDeskewing {
            get {
                return ResourceManager.GetString("AutoDeskewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deskew Progress ähnelt.
        /// </summary>
        internal static string AutoDeskewProgress {
            get {
                return ResourceManager.GetString("AutoDeskewProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred when trying to auto save. ähnelt.
        /// </summary>
        internal static string AutoSaveError {
            get {
                return ResourceManager.GetString("AutoSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unknown error ocurred during the batch scan. ähnelt.
        /// </summary>
        internal static string BatchError {
            get {
                return ResourceManager.GetString("BatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch cancelled. ähnelt.
        /// </summary>
        internal static string BatchStatusCancelled {
            get {
                return ResourceManager.GetString("BatchStatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancelling.... ähnelt.
        /// </summary>
        internal static string BatchStatusCancelling {
            get {
                return ResourceManager.GetString("BatchStatusCancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch completed successfully. ähnelt.
        /// </summary>
        internal static string BatchStatusComplete {
            get {
                return ResourceManager.GetString("BatchStatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch scan stopped due to error. ähnelt.
        /// </summary>
        internal static string BatchStatusError {
            get {
                return ResourceManager.GetString("BatchStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning page {0}... ähnelt.
        /// </summary>
        internal static string BatchStatusPage {
            get {
                return ResourceManager.GetString("BatchStatusPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving batch results... ähnelt.
        /// </summary>
        internal static string BatchStatusSaving {
            get {
                return ResourceManager.GetString("BatchStatusSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning page {0} (scan {1})... ähnelt.
        /// </summary>
        internal static string BatchStatusScanPage {
            get {
                return ResourceManager.GetString("BatchStatusScanPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for scan {0}... ähnelt.
        /// </summary>
        internal static string BatchStatusWaitingForScan {
            get {
                return ResourceManager.GetString("BatchStatusWaitingForScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel Batch ähnelt.
        /// </summary>
        internal static string CancelBatch {
            get {
                return ResourceManager.GetString("CancelBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking... ähnelt.
        /// </summary>
        internal static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Profile ähnelt.
        /// </summary>
        internal static string ChooseProfile {
            get {
                return ResourceManager.GetString("ChooseProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to cancel the batch scan? ähnelt.
        /// </summary>
        internal static string ConfirmCancelBatch {
            get {
                return ResourceManager.GetString("ConfirmCancelBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to clear {0} item(s)? ähnelt.
        /// </summary>
        internal static string ConfirmClearItems {
            get {
                return ResourceManager.GetString("ConfirmClearItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete &quot;{0}&quot;? ähnelt.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete {0} item(s)? ähnelt.
        /// </summary>
        internal static string ConfirmDeleteItems {
            get {
                return ResourceManager.GetString("ConfirmDeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete {0} profiles? ähnelt.
        /// </summary>
        internal static string ConfirmDeleteMultipleProfiles {
            get {
                return ResourceManager.GetString("ConfirmDeleteMultipleProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete the profile {0}? ähnelt.
        /// </summary>
        internal static string ConfirmDeleteSingleProfile {
            get {
                return ResourceManager.GetString("ConfirmDeleteSingleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file {0} already exists. Do you want to overwrite it? ähnelt.
        /// </summary>
        internal static string ConfirmOverwriteFile {
            get {
                return ResourceManager.GetString("ConfirmOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want undo your changes to {0} image(s)? ähnelt.
        /// </summary>
        internal static string ConfirmResetImages {
            get {
                return ResourceManager.GetString("ConfirmResetImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copying... ähnelt.
        /// </summary>
        internal static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy Progress ähnelt.
        /// </summary>
        internal static string CopyProgress {
            get {
                return ResourceManager.GetString("CopyProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom ({0}x{1} {2}) ähnelt.
        /// </summary>
        internal static string CustomPageSizeFormat {
            get {
                return ResourceManager.GetString("CustomPageSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detecting Barcodes... ähnelt.
        /// </summary>
        internal static string DetectBarcodeMessage {
            get {
                return ResourceManager.GetString("DetectBarcodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detect Barcodes Progress ähnelt.
        /// </summary>
        internal static string DetectBarcodeProgress {
            get {
                return ResourceManager.GetString("DetectBarcodeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected scanner is busy. ähnelt.
        /// </summary>
        internal static string DeviceBusy {
            get {
                return ResourceManager.GetString("DeviceBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The scanner&apos;s cover is open. ähnelt.
        /// </summary>
        internal static string DeviceCoverOpen {
            get {
                return ResourceManager.GetString("DeviceCoverOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected scanner could not be found. ähnelt.
        /// </summary>
        internal static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected scanner is offline. ähnelt.
        /// </summary>
        internal static string DeviceOffline {
            get {
                return ResourceManager.GetString("DeviceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The scanner has a paper jam. ähnelt.
        /// </summary>
        internal static string DevicePaperJam {
            get {
                return ResourceManager.GetString("DevicePaperJam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The scanner is warming up. ähnelt.
        /// </summary>
        internal static string DeviceWarmingUp {
            get {
                return ResourceManager.GetString("DeviceWarmingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Donate ähnelt.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NAPS2 is completely free. Consider making a donation. ähnelt.
        /// </summary>
        internal static string DonatePrompt {
            get {
                return ResourceManager.GetString("DonatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You don&apos;t have permission to save files at this location. ähnelt.
        /// </summary>
        internal static string DontHavePermission {
            get {
                return ResourceManager.GetString("DontHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Error ähnelt.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Needed ähnelt.
        /// </summary>
        internal static string DownloadNeeded {
            get {
                return ResourceManager.GetString("DownloadNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected driver is not supported on this system. ähnelt.
        /// </summary>
        internal static string DriverNotSupported {
            get {
                return ResourceManager.GetString("DriverNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred while trying to send an email. ähnelt.
        /// </summary>
        internal static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email PDF ähnelt.
        /// </summary>
        internal static string EmailPdf {
            get {
                return ResourceManager.GetString("EmailPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email PDF Progress ähnelt.
        /// </summary>
        internal static string EmailPdfProgress {
            get {
                return ResourceManager.GetString("EmailPdfProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred when trying to send the email. ähnelt.
        /// </summary>
        internal static string ErrorEmailing {
            get {
                return ResourceManager.GetString("ErrorEmailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred when trying to save the file. ähnelt.
        /// </summary>
        internal static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Error occurred while uploading to DOCUMENTS ähnelt.
        /// </summary>
        internal static string ErrorUploading {
            get {
                return ResourceManager.GetString("ErrorUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Estimated download size: {0} MB ähnelt.
        /// </summary>
        internal static string EstimatedDownloadSize {
            get {
                return ResourceManager.GetString("EstimatedDownloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An operation is in progress. Are you sure you want to exit and cancel the operation? ähnelt.
        /// </summary>
        internal static string ExitWithActiveOperations {
            get {
                return ResourceManager.GetString("ExitWithActiveOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have unsaved changes. Are you sure you want to exit and discard those changes? ähnelt.
        /// </summary>
        internal static string ExitWithUnsavedChanges {
            get {
                return ResourceManager.GetString("ExitWithUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file could not be overwritten because it is currently in use. ähnelt.
        /// </summary>
        internal static string FileInUse {
            get {
                return ResourceManager.GetString("FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more files could not be downloaded. ähnelt.
        /// </summary>
        internal static string FilesCouldNotBeDownloaded {
            get {
                return ResourceManager.GetString("FilesCouldNotBeDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} / {1} files ähnelt.
        /// </summary>
        internal static string FilesProgressFormat {
            get {
                return ResourceManager.GetString("FilesProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Files ähnelt.
        /// </summary>
        internal static string FileTypeAllFiles {
            get {
                return ResourceManager.GetString("FileTypeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitmap Files (*.bmp) ähnelt.
        /// </summary>
        internal static string FileTypeBmp {
            get {
                return ResourceManager.GetString("FileTypeBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enhanced Windows MetaFile (*.emf) ähnelt.
        /// </summary>
        internal static string FileTypeEmf {
            get {
                return ResourceManager.GetString("FileTypeEmf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exchangeable Image File (*.exif) ähnelt.
        /// </summary>
        internal static string FileTypeExif {
            get {
                return ResourceManager.GetString("FileTypeExif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GIF File (*.gif) ähnelt.
        /// </summary>
        internal static string FileTypeGif {
            get {
                return ResourceManager.GetString("FileTypeGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Files ähnelt.
        /// </summary>
        internal static string FileTypeImageFiles {
            get {
                return ResourceManager.GetString("FileTypeImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JPEG File (*.jpg, *.jpeg) ähnelt.
        /// </summary>
        internal static string FileTypeJpeg {
            get {
                return ResourceManager.GetString("FileTypeJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF Document (*.pdf) ähnelt.
        /// </summary>
        internal static string FileTypePdf {
            get {
                return ResourceManager.GetString("FileTypePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PNG File (*.png) ähnelt.
        /// </summary>
        internal static string FileTypePng {
            get {
                return ResourceManager.GetString("FileTypePng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TIFF File (*.tiff, *.tif) ähnelt.
        /// </summary>
        internal static string FileTypeTiff {
            get {
                return ResourceManager.GetString("FileTypeTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image saved. ähnelt.
        /// </summary>
        internal static string ImageSaved {
            get {
                return ResourceManager.GetString("ImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} images saved. ähnelt.
        /// </summary>
        internal static string ImagesSaved {
            get {
                return ResourceManager.GetString("ImagesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; could not be imported. ähnelt.
        /// </summary>
        internal static string ImportErrorCouldNot {
            get {
                return ResourceManager.GetString("ImportErrorCouldNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; could not be imported. Only PDF files generated by NAPS2 can be imported. ähnelt.
        /// </summary>
        internal static string ImportErrorNAPS2Pdf {
            get {
                return ResourceManager.GetString("ImportErrorNAPS2Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importing... ähnelt.
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importing {0}... ähnelt.
        /// </summary>
        internal static string ImportingFormat {
            get {
                return ResourceManager.GetString("ImportingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Progress ähnelt.
        /// </summary>
        internal static string ImportProgress {
            get {
                return ResourceManager.GetString("ImportProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install {0} ähnelt.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation Complete ähnelt.
        /// </summary>
        internal static string InstallComplete {
            get {
                return ResourceManager.GetString("InstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation complete. Do you want to restart NAPS2 now? ähnelt.
        /// </summary>
        internal static string InstallCompletePromptRestart {
            get {
                return ResourceManager.GetString("InstallCompletePromptRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation failed. ähnelt.
        /// </summary>
        internal static string InstallFailed {
            get {
                return ResourceManager.GetString("InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installation Failed ähnelt.
        /// </summary>
        internal static string InstallFailedTitle {
            get {
                return ResourceManager.GetString("InstallFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Listening on port {0} ähnelt.
        /// </summary>
        internal static string ListeningOnPort {
            get {
                return ResourceManager.GetString("ListeningOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ({1}x{2} {3}) ähnelt.
        /// </summary>
        internal static string NamedPageSizeFormat {
            get {
                return ResourceManager.GetString("NamedPageSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name missing. ähnelt.
        /// </summary>
        internal static string NameMissing {
            get {
                return ResourceManager.GetString("NameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NAPS2 ähnelt.
        /// </summary>
        internal static string NAPS2 {
            get {
                return ResourceManager.GetString("NAPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NAPS2 Server ähnelt.
        /// </summary>
        internal static string Naps2Server {
            get {
                return ResourceManager.GetString("Naps2Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No device selected. ähnelt.
        /// </summary>
        internal static string NoDeviceSelected {
            get {
                return ResourceManager.GetString("NoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No scanning device was found. ähnelt.
        /// </summary>
        internal static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected scanner does not support using duplex. If your scanner is supposed to support duplex, try using a different driver. ähnelt.
        /// </summary>
        internal static string NoDuplexSupport {
            get {
                return ResourceManager.GetString("NoDuplexSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected scanner does not support using a feeder. If your scanner does have a feeder, try using a different driver. ähnelt.
        /// </summary>
        internal static string NoFeederSupport {
            get {
                return ResourceManager.GetString("NoFeederSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No pages are in the feeder. ähnelt.
        /// </summary>
        internal static string NoPagesInFeeder {
            get {
                return ResourceManager.GetString("NoPagesInFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No updates available. ähnelt.
        /// </summary>
        internal static string NoUpdates {
            get {
                return ResourceManager.GetString("NoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OCR Progress ähnelt.
        /// </summary>
        internal static string OcrProgress {
            get {
                return ResourceManager.GetString("OcrProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An update to OCR is available. ähnelt.
        /// </summary>
        internal static string OcrUpdateAvailable {
            get {
                return ResourceManager.GetString("OcrUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die of {0} ähnelt.
        /// </summary>
        internal static string OfN {
            get {
                return ResourceManager.GetString("OfN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite File ähnelt.
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An additional component is needed to import this PDF file. Would you like to download it now? ähnelt.
        /// </summary>
        internal static string PdfImportComponentNeeded {
            get {
                return ResourceManager.GetString("PdfImportComponentNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You do not have permission to copy content from the file &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string PdfNoPermissionToExtractContent {
            get {
                return ResourceManager.GetString("PdfNoPermissionToExtractContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF saved. ähnelt.
        /// </summary>
        internal static string PdfSaved {
            get {
                return ResourceManager.GetString("PdfSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of {1} ähnelt.
        /// </summary>
        internal static string PdfStatus {
            get {
                return ResourceManager.GetString("PdfStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} / {1} ähnelt.
        /// </summary>
        internal static string ProgressFormat {
            get {
                return ResourceManager.GetString("ProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recovering... ähnelt.
        /// </summary>
        internal static string Recovering {
            get {
                return ResourceManager.GetString("Recovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recovery Progress ähnelt.
        /// </summary>
        internal static string RecoveryProgress {
            get {
                return ResourceManager.GetString("RecoveryProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Image ähnelt.
        /// </summary>
        internal static string ResetImage {
            get {
                return ResourceManager.GetString("ResetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Running OCR... ähnelt.
        /// </summary>
        internal static string RunningOcr {
            get {
                return ResourceManager.GetString("RunningOcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The SANE driver is not available. Make sure to install the required packages: ähnelt.
        /// </summary>
        internal static string SaneNotAvailable {
            get {
                return ResourceManager.GetString("SaneNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Images ähnelt.
        /// </summary>
        internal static string SaveImages {
            get {
                return ResourceManager.GetString("SaveImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Images Progress ähnelt.
        /// </summary>
        internal static string SaveImagesProgress {
            get {
                return ResourceManager.GetString("SaveImagesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save PDF ähnelt.
        /// </summary>
        internal static string SavePdf {
            get {
                return ResourceManager.GetString("SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save PDF Progress ähnelt.
        /// </summary>
        internal static string SavePdfProgress {
            get {
                return ResourceManager.GetString("SavePdfProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving {0}... ähnelt.
        /// </summary>
        internal static string SavingFormat {
            get {
                return ResourceManager.GetString("SavingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan ähnelt.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanned Image ähnelt.
        /// </summary>
        internal static string ScannedImage {
            get {
                return ResourceManager.GetString("ScannedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning page {0} ähnelt.
        /// </summary>
        internal static string ScanPageProgress {
            get {
                return ResourceManager.GetString("ScanPageProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanning page {0}... ähnelt.
        /// </summary>
        internal static string ScanProgressPage {
            get {
                return ResourceManager.GetString("ScanProgressPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected ({0}) ähnelt.
        /// </summary>
        internal static string SelectedCount {
            get {
                return ResourceManager.GetString("SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a profile before clicking Scan. ähnelt.
        /// </summary>
        internal static string SelectProfileBeforeScan {
            get {
                return ResourceManager.GetString("SelectProfileBeforeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server started ähnelt.
        /// </summary>
        internal static string ServerStarted {
            get {
                return ResourceManager.GetString("ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} / {1} MB ähnelt.
        /// </summary>
        internal static string SizeProgress {
            get {
                return ResourceManager.GetString("SizeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The OCR engine is not available. Make sure to install the required package: ähnelt.
        /// </summary>
        internal static string TesseractNotAvailable {
            get {
                return ResourceManager.GetString("TesseractNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred with the scanning driver. ähnelt.
        /// </summary>
        internal static string UnknownDriverError {
            get {
                return ResourceManager.GetString("UnknownDriverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsaved Changes ähnelt.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An update is available. ähnelt.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured when trying to install the update. ähnelt.
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Progress ähnelt.
        /// </summary>
        internal static string UpdateProgress {
            get {
                return ResourceManager.GetString("UpdateProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating... ähnelt.
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploading to DOCUMENTS... ähnelt.
        /// </summary>
        internal static string UploadingDocuments {
            get {
                return ResourceManager.GetString("UploadingDocuments", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploading to Squeeze... ähnelt.
        /// </summary>
        internal static string UploadingSqueeze
        {
            get
            {
                return ResourceManager.GetString("UploadingSqueeze", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploading email... ähnelt.
        /// </summary>
        internal static string UploadingEmail {
            get {
                return ResourceManager.GetString("UploadingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload PDF Progress ähnelt.
        /// </summary>
        internal static string UploadPdfProgress {
            get {
                return ResourceManager.GetString("UploadPdfProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version {0} ähnelt.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
