//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.Resources.SettingsResources", typeof(SettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Black &amp; White ähnelt.
        /// </summary>
        internal static string BitDepth_1BlackAndWhite {
            get {
                return ResourceManager.GetString("BitDepth_1BlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 24-bit Color ähnelt.
        /// </summary>
        internal static string BitDepth_24Color {
            get {
                return ResourceManager.GetString("BitDepth_24Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grayscale ähnelt.
        /// </summary>
        internal static string BitDepth_8Grayscale {
            get {
                return ResourceManager.GetString("BitDepth_8Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 100 dpi ähnelt.
        /// </summary>
        internal static string Dpi_100 {
            get {
                return ResourceManager.GetString("Dpi_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1200 dpi ähnelt.
        /// </summary>
        internal static string Dpi_1200 {
            get {
                return ResourceManager.GetString("Dpi_1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 150 dpi ähnelt.
        /// </summary>
        internal static string Dpi_150 {
            get {
                return ResourceManager.GetString("Dpi_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 200 dpi ähnelt.
        /// </summary>
        internal static string Dpi_200 {
            get {
                return ResourceManager.GetString("Dpi_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 300 dpi ähnelt.
        /// </summary>
        internal static string Dpi_300 {
            get {
                return ResourceManager.GetString("Dpi_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 400 dpi ähnelt.
        /// </summary>
        internal static string Dpi_400 {
            get {
                return ResourceManager.GetString("Dpi_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 600 dpi ähnelt.
        /// </summary>
        internal static string Dpi_600 {
            get {
                return ResourceManager.GetString("Dpi_600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 800 dpi ähnelt.
        /// </summary>
        internal static string Dpi_800 {
            get {
                return ResourceManager.GetString("Dpi_800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No provider selected. ähnelt.
        /// </summary>
        internal static string EmailProvider_NotSelected {
            get {
                return ResourceManager.GetString("EmailProvider_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom SMTP ähnelt.
        /// </summary>
        internal static string EmailProviderType_CustomSmtp {
            get {
                return ResourceManager.GetString("EmailProviderType_CustomSmtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gmail ähnelt.
        /// </summary>
        internal static string EmailProviderType_Gmail {
            get {
                return ResourceManager.GetString("EmailProviderType_Gmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outlook Web Access ähnelt.
        /// </summary>
        internal static string EmailProviderType_OutlookWeb {
            get {
                return ResourceManager.GetString("EmailProviderType_OutlookWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Center ähnelt.
        /// </summary>
        internal static string HorizontalAlign_Center {
            get {
                return ResourceManager.GetString("HorizontalAlign_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left ähnelt.
        /// </summary>
        internal static string HorizontalAlign_Left {
            get {
                return ResourceManager.GetString("HorizontalAlign_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right ähnelt.
        /// </summary>
        internal static string HorizontalAlign_Right {
            get {
                return ResourceManager.GetString("HorizontalAlign_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A3 (297x420 mm) ähnelt.
        /// </summary>
        internal static string PageSize_A3 {
            get {
                return ResourceManager.GetString("PageSize_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A4 (210x297 mm) ähnelt.
        /// </summary>
        internal static string PageSize_A4 {
            get {
                return ResourceManager.GetString("PageSize_A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A5 (148x210 mm) ähnelt.
        /// </summary>
        internal static string PageSize_A5 {
            get {
                return ResourceManager.GetString("PageSize_A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die B4 (250x353 mm) ähnelt.
        /// </summary>
        internal static string PageSize_B4 {
            get {
                return ResourceManager.GetString("PageSize_B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die B5 (176x250 mm) ähnelt.
        /// </summary>
        internal static string PageSize_B5 {
            get {
                return ResourceManager.GetString("PageSize_B5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom... ähnelt.
        /// </summary>
        internal static string PageSize_Custom {
            get {
                return ResourceManager.GetString("PageSize_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die US Legal (8.5x14 in) ähnelt.
        /// </summary>
        internal static string PageSize_Legal {
            get {
                return ResourceManager.GetString("PageSize_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die US Letter (8.5x11 in) ähnelt.
        /// </summary>
        internal static string PageSize_Letter {
            get {
                return ResourceManager.GetString("PageSize_Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cm ähnelt.
        /// </summary>
        internal static string PageSizeUnit_Centimetre {
            get {
                return ResourceManager.GetString("PageSizeUnit_Centimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die in ähnelt.
        /// </summary>
        internal static string PageSizeUnit_Inch {
            get {
                return ResourceManager.GetString("PageSizeUnit_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mm ähnelt.
        /// </summary>
        internal static string PageSizeUnit_Millimetre {
            get {
                return ResourceManager.GetString("PageSizeUnit_Millimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        internal static string PdfCompat_Default {
            get {
                return ResourceManager.GetString("PdfCompat_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF/A-1b ähnelt.
        /// </summary>
        internal static string PdfCompat_PdfA1B {
            get {
                return ResourceManager.GetString("PdfCompat_PdfA1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF/A-2b ähnelt.
        /// </summary>
        internal static string PdfCompat_PdfA2B {
            get {
                return ResourceManager.GetString("PdfCompat_PdfA2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF/A-3b ähnelt.
        /// </summary>
        internal static string PdfCompat_PdfA3B {
            get {
                return ResourceManager.GetString("PdfCompat_PdfA3B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF/A-3u ähnelt.
        /// </summary>
        internal static string PdfCompat_PdfA3U {
            get {
                return ResourceManager.GetString("PdfCompat_PdfA3U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1:1 ähnelt.
        /// </summary>
        internal static string Scale_1_1 {
            get {
                return ResourceManager.GetString("Scale_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1:2 ähnelt.
        /// </summary>
        internal static string Scale_1_2 {
            get {
                return ResourceManager.GetString("Scale_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1:4 ähnelt.
        /// </summary>
        internal static string Scale_1_4 {
            get {
                return ResourceManager.GetString("Scale_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1:8 ähnelt.
        /// </summary>
        internal static string Scale_1_8 {
            get {
                return ResourceManager.GetString("Scale_1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplex ähnelt.
        /// </summary>
        internal static string Source_Duplex {
            get {
                return ResourceManager.GetString("Source_Duplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feeder ähnelt.
        /// </summary>
        internal static string Source_Feeder {
            get {
                return ResourceManager.GetString("Source_Feeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glass ähnelt.
        /// </summary>
        internal static string Source_Glass {
            get {
                return ResourceManager.GetString("Source_Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto ähnelt.
        /// </summary>
        internal static string TiffComp_Auto {
            get {
                return ResourceManager.GetString("TiffComp_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CCITT4 ähnelt.
        /// </summary>
        internal static string TiffComp_Ccitt4 {
            get {
                return ResourceManager.GetString("TiffComp_Ccitt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LZW ähnelt.
        /// </summary>
        internal static string TiffComp_Lzw {
            get {
                return ResourceManager.GetString("TiffComp_Lzw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string TiffComp_None {
            get {
                return ResourceManager.GetString("TiffComp_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        internal static string TwainImpl_Default {
            get {
                return ResourceManager.GetString("TwainImpl_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legacy (native UI only) ähnelt.
        /// </summary>
        internal static string TwainImpl_Legacy {
            get {
                return ResourceManager.GetString("TwainImpl_Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alternative Transfer ähnelt.
        /// </summary>
        internal static string TwainImpl_MemXfer {
            get {
                return ResourceManager.GetString("TwainImpl_MemXfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old DSM ähnelt.
        /// </summary>
        internal static string TwainImpl_OldDsm {
            get {
                return ResourceManager.GetString("TwainImpl_OldDsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die x64 ähnelt.
        /// </summary>
        internal static string TwainImpl_X64 {
            get {
                return ResourceManager.GetString("TwainImpl_X64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        internal static string WiaVersion_Default {
            get {
                return ResourceManager.GetString("WiaVersion_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1.0 ähnelt.
        /// </summary>
        internal static string WiaVersion_Wia10 {
            get {
                return ResourceManager.GetString("WiaVersion_Wia10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2.0 ähnelt.
        /// </summary>
        internal static string WiaVersion_Wia20 {
            get {
                return ResourceManager.GetString("WiaVersion_Wia20", resourceCulture);
            }
        }
    }
}
