//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.Resources.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string AboutFormTitle {
            get {
                return ResourceManager.GetString("AboutFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced Profile Settings ähnelt.
        /// </summary>
        internal static string AdvancedProfileFormTitle {
            get {
                return ResourceManager.GetString("AdvancedProfileFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow Annotations ähnelt.
        /// </summary>
        internal static string AllowAnnotations {
            get {
                return ResourceManager.GetString("AllowAnnotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow Content Copying ähnelt.
        /// </summary>
        internal static string AllowContentCopying {
            get {
                return ResourceManager.GetString("AllowContentCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow Content Copying for Accessibility ähnelt.
        /// </summary>
        internal static string AllowContentCopyingForAccessibility {
            get {
                return ResourceManager.GetString("AllowContentCopyingForAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow Document Assembly ähnelt.
        /// </summary>
        internal static string AllowDocumentAssembly {
            get {
                return ResourceManager.GetString("AllowDocumentAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow Document Modification ähnelt.
        /// </summary>
        internal static string AllowDocumentModification {
            get {
                return ResourceManager.GetString("AllowDocumentModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow Form Filling ähnelt.
        /// </summary>
        internal static string AllowFormFilling {
            get {
                return ResourceManager.GetString("AllowFormFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow Full Quality Printing ähnelt.
        /// </summary>
        internal static string AllowFullQualityPrinting {
            get {
                return ResourceManager.GetString("AllowFullQualityPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow Printing ähnelt.
        /// </summary>
        internal static string AllowPrinting {
            get {
                return ResourceManager.GetString("AllowPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alternate Deinterleave ähnelt.
        /// </summary>
        internal static string AltDeinterleave {
            get {
                return ResourceManager.GetString("AltDeinterleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alternate Interleave ähnelt.
        /// </summary>
        internal static string AltInterleave {
            get {
                return ResourceManager.GetString("AltInterleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apple Driver ähnelt.
        /// </summary>
        internal static string AppleDriver {
            get {
                return ResourceManager.GetString("AppleDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application ähnelt.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply to all {0} selected images ähnelt.
        /// </summary>
        internal static string ApplyToSelected {
            get {
                return ResourceManager.GetString("ApplyToSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attachment Name: ähnelt.
        /// </summary>
        internal static string AttachmentNameLabel {
            get {
                return ResourceManager.GetString("AttachmentNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authorize ähnelt.
        /// </summary>
        internal static string AuthorizeFormTitle {
            get {
                return ResourceManager.GetString("AuthorizeFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author: ähnelt.
        /// </summary>
        internal static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-incrementing number (1 digits) ähnelt.
        /// </summary>
        internal static string AutoIncrementing1Digit {
            get {
                return ResourceManager.GetString("AutoIncrementing1Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-incrementing number (2 digits) ähnelt.
        /// </summary>
        internal static string AutoIncrementing2Digit {
            get {
                return ResourceManager.GetString("AutoIncrementing2Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-incrementing number (3 digits) ähnelt.
        /// </summary>
        internal static string AutoIncrementing3Digit {
            get {
                return ResourceManager.GetString("AutoIncrementing3Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-incrementing number (4 digits) ähnelt.
        /// </summary>
        internal static string AutoIncrementing4Digit {
            get {
                return ResourceManager.GetString("AutoIncrementing4Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Save Settings ähnelt.
        /// </summary>
        internal static string AutoSaveSettings {
            get {
                return ResourceManager.GetString("AutoSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Save Settings ähnelt.
        /// </summary>
        internal static string AutoSaveSettingsFormTitle {
            get {
                return ResourceManager.GetString("AutoSaveSettingsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Scan ähnelt.
        /// </summary>
        internal static string BatchPromptFormTitle {
            get {
                return ResourceManager.GetString("BatchPromptFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch Scan ähnelt.
        /// </summary>
        internal static string BatchScan {
            get {
                return ResourceManager.GetString("BatchScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch Scan ähnelt.
        /// </summary>
        internal static string BatchScanFormTitle {
            get {
                return ResourceManager.GetString("BatchScanFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bit depth: ähnelt.
        /// </summary>
        internal static string BitDepthLabel {
            get {
                return ResourceManager.GetString("BitDepthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Black and White ähnelt.
        /// </summary>
        internal static string BlackAndWhite {
            get {
                return ResourceManager.GetString("BlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blank Pages ähnelt.
        /// </summary>
        internal static string BlankPages {
            get {
                return ResourceManager.GetString("BlankPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brightness / Contrast ähnelt.
        /// </summary>
        internal static string BrightnessContrast {
            get {
                return ResourceManager.GetString("BrightnessContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply brightness/contrast after scan ähnelt.
        /// </summary>
        internal static string BrightnessContrastAfterScan {
            get {
                return ResourceManager.GetString("BrightnessContrastAfterScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brightness: ähnelt.
        /// </summary>
        internal static string BrightnessLabel {
            get {
                return ResourceManager.GetString("BrightnessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for updates ähnelt.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose device ähnelt.
        /// </summary>
        internal static string ChooseDevice {
            get {
                return ResourceManager.GetString("ChooseDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear images after saving ähnelt.
        /// </summary>
        internal static string ClearAfterSaving {
            get {
                return ResourceManager.GetString("ClearAfterSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear All ähnelt.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client ähnelt.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compatibility ähnelt.
        /// </summary>
        internal static string Compatibility {
            get {
                return ResourceManager.GetString("Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compression: ähnelt.
        /// </summary>
        internal static string CompressionLabel {
            get {
                return ResourceManager.GetString("CompressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to stop sharing {0}? ähnelt.
        /// </summary>
        internal static string ConfirmDeleteSharedDevice {
            get {
                return ResourceManager.GetString("ConfirmDeleteSharedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contrast: ähnelt.
        /// </summary>
        internal static string ContrastLabel {
            get {
                return ResourceManager.GetString("ContrastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright {0} NAPS2 Contributors ähnelt.
        /// </summary>
        internal static string CopyrightFormat {
            get {
                return ResourceManager.GetString("CopyrightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coverage Threshold ähnelt.
        /// </summary>
        internal static string CoverageThreshold {
            get {
                return ResourceManager.GetString("CoverageThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crop ähnelt.
        /// </summary>
        internal static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crop to page size ähnelt.
        /// </summary>
        internal static string CropToPageSize {
            get {
                return ResourceManager.GetString("CropToPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Rotation ähnelt.
        /// </summary>
        internal static string CustomRotation {
            get {
                return ResourceManager.GetString("CustomRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day (01-31) ähnelt.
        /// </summary>
        internal static string Day2Digit {
            get {
                return ResourceManager.GetString("Day2Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default File Path: ähnelt.
        /// </summary>
        internal static string DefaultFilePathLabel {
            get {
                return ResourceManager.GetString("DefaultFilePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deinterleave ähnelt.
        /// </summary>
        internal static string Deinterleave {
            get {
                return ResourceManager.GetString("Deinterleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deskew ähnelt.
        /// </summary>
        internal static string Deskew {
            get {
                return ResourceManager.GetString("Deskew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deskew scanned pages ähnelt.
        /// </summary>
        internal static string DeskewScannedPages {
            get {
                return ResourceManager.GetString("DeskewScannedPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device: ähnelt.
        /// </summary>
        internal static string DeviceLabel {
            get {
                return ResourceManager.GetString("DeviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dimensions ähnelt.
        /// </summary>
        internal static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display name: ähnelt.
        /// </summary>
        internal static string DisplayNameLabel {
            get {
                return ResourceManager.GetString("DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document Correction ähnelt.
        /// </summary>
        internal static string DocumentCorrection {
            get {
                return ResourceManager.GetString("DocumentCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Donate ähnelt.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done ähnelt.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Progress ähnelt.
        /// </summary>
        internal static string DownloadProgressFormTitle {
            get {
                return ResourceManager.GetString("DownloadProgressFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile Settings ähnelt.
        /// </summary>
        internal static string EditProfileFormTitle {
            get {
                return ResourceManager.GetString("EditProfileFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... ähnelt.
        /// </summary>
        internal static string Ellipsis {
            get {
                return ResourceManager.GetString("Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email All ähnelt.
        /// </summary>
        internal static string EmailAll {
            get {
                return ResourceManager.GetString("EmailAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email All as PDF ähnelt.
        /// </summary>
        internal static string EmailAllAsPdf {
            get {
                return ResourceManager.GetString("EmailAllAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email PDF ähnelt.
        /// </summary>
        internal static string EmailPdf {
            get {
                return ResourceManager.GetString("EmailPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Email Provider ähnelt.
        /// </summary>
        internal static string EmailProviderFormTitle {
            get {
                return ResourceManager.GetString("EmailProviderFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email Selected ähnelt.
        /// </summary>
        internal static string EmailSelected {
            get {
                return ResourceManager.GetString("EmailSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email Selected as PDF ähnelt.
        /// </summary>
        internal static string EmailSelectedAsPdf {
            get {
                return ResourceManager.GetString("EmailSelectedAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email Settings ähnelt.
        /// </summary>
        internal static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email Settings ähnelt.
        /// </summary>
        internal static string EmailSettingsFormTitle {
            get {
                return ResourceManager.GetString("EmailSettingsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Auto Save ähnelt.
        /// </summary>
        internal static string EnableAutoSave {
            get {
                return ResourceManager.GetString("EnableAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable debug logging ähnelt.
        /// </summary>
        internal static string EnableDebugLogging {
            get {
                return ResourceManager.GetString("EnableDebugLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following file is encrypted and requires a password to open: ähnelt.
        /// </summary>
        internal static string EncryptedFilePrompt {
            get {
                return ResourceManager.GetString("EncryptedFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encryption ähnelt.
        /// </summary>
        internal static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encrypt PDF ähnelt.
        /// </summary>
        internal static string EncryptPdf {
            get {
                return ResourceManager.GetString("EncryptPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string ErrorFormTitle {
            get {
                return ResourceManager.GetString("ErrorFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ESCL Driver ähnelt.
        /// </summary>
        internal static string EsclDriver {
            get {
                return ResourceManager.GetString("EsclDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ESCL Network Driver ähnelt.
        /// </summary>
        internal static string EsclNetworkDriver {
            get {
                return ResourceManager.GetString("EsclNetworkDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ESCL USB Driver ähnelt.
        /// </summary>
        internal static string EsclUsbDriver {
            get {
                return ResourceManager.GetString("EsclUsbDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Estimated download size: {0} MB ähnelt.
        /// </summary>
        internal static string EstimatedDownloadSize {
            get {
                return ResourceManager.GetString("EstimatedDownloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exclude blank pages ähnelt.
        /// </summary>
        internal static string ExcludeBlankPages {
            get {
                return ResourceManager.GetString("ExcludeBlankPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Name: ähnelt.
        /// </summary>
        internal static string FileNameLabel {
            get {
                return ResourceManager.GetString("FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Path: ähnelt.
        /// </summary>
        internal static string FilePathLabel {
            get {
                return ResourceManager.GetString("FilePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flip ähnelt.
        /// </summary>
        internal static string Flip {
            get {
                return ResourceManager.GetString("Flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flip duplexed pages ähnelt.
        /// </summary>
        internal static string FlipDuplexedPages {
            get {
                return ResourceManager.GetString("FlipDuplexedPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get more languages ähnelt.
        /// </summary>
        internal static string GetMoreLanguages {
            get {
                return ResourceManager.GetString("GetMoreLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horizontal align: ähnelt.
        /// </summary>
        internal static string HorizontalAlignLabel {
            get {
                return ResourceManager.GetString("HorizontalAlignLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hour (0-23) ähnelt.
        /// </summary>
        internal static string Hour2Digit {
            get {
                return ResourceManager.GetString("Hour2Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hue / Saturation ähnelt.
        /// </summary>
        internal static string HueSaturation {
            get {
                return ResourceManager.GetString("HueSaturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icons from: ähnelt.
        /// </summary>
        internal static string IconsFrom {
            get {
                return ResourceManager.GetString("IconsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image ähnelt.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Quality ähnelt.
        /// </summary>
        internal static string ImageQuality {
            get {
                return ResourceManager.GetString("ImageQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Settings ähnelt.
        /// </summary>
        internal static string ImageSettings {
            get {
                return ResourceManager.GetString("ImageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Settings ähnelt.
        /// </summary>
        internal static string ImageSettingsFormTitle {
            get {
                return ResourceManager.GetString("ImageSettingsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interface ähnelt.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interleave ähnelt.
        /// </summary>
        internal static string Interleave {
            get {
                return ResourceManager.GetString("Interleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jpeg Quality ähnelt.
        /// </summary>
        internal static string JpegQuality {
            get {
                return ResourceManager.GetString("JpegQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For high JPEG qualities (80+), also increase Image Quality in your profile for best results. ähnelt.
        /// </summary>
        internal static string JpegQualityHelp {
            get {
                return ResourceManager.GetString("JpegQualityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keep images across sessions ähnelt.
        /// </summary>
        internal static string KeepSession {
            get {
                return ResourceManager.GetString("KeepSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keep Settings ähnelt.
        /// </summary>
        internal static string KeepSettings {
            get {
                return ResourceManager.GetString("KeepSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keywords: ähnelt.
        /// </summary>
        internal static string KeywordsLabel {
            get {
                return ResourceManager.GetString("KeywordsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load images into NAPS2 ähnelt.
        /// </summary>
        internal static string LoadIn {
            get {
                return ResourceManager.GetString("LoadIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Make PDFs searchable using OCR ähnelt.
        /// </summary>
        internal static string MakePdfsSearchable {
            get {
                return ResourceManager.GetString("MakePdfsSearchable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum quality (large files) ähnelt.
        /// </summary>
        internal static string MaximumQuality {
            get {
                return ResourceManager.GetString("MaximumQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metadata ähnelt.
        /// </summary>
        internal static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minute (00-59) ähnelt.
        /// </summary>
        internal static string Minute2Digit {
            get {
                return ResourceManager.GetString("Minute2Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month (01-12) ähnelt.
        /// </summary>
        internal static string Month2Digit {
            get {
                return ResourceManager.GetString("Month2Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More info ähnelt.
        /// </summary>
        internal static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Down ähnelt.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Up ähnelt.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiple scans (fixed delay between scans) ähnelt.
        /// </summary>
        internal static string MultipleScansDelay {
            get {
                return ResourceManager.GetString("MultipleScansDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiple scans (prompt between scans) ähnelt.
        /// </summary>
        internal static string MultipleScansPrompt {
            get {
                return ResourceManager.GetString("MultipleScansPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name (optional) ähnelt.
        /// </summary>
        internal static string NameOptional {
            get {
                return ResourceManager.GetString("NameOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NAPS2 ähnelt.
        /// </summary>
        internal static string Naps2 {
            get {
                return ResourceManager.GetString("Naps2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Another PDF Scanner ähnelt.
        /// </summary>
        internal static string Naps2FullName {
            get {
                return ResourceManager.GetString("Naps2FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NAPS2 - {0} ähnelt.
        /// </summary>
        internal static string Naps2TitleFormat {
            get {
                return ResourceManager.GetString("Naps2TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Profile ähnelt.
        /// </summary>
        internal static string NewProfile {
            get {
                return ResourceManager.GetString("NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Now ähnelt.
        /// </summary>
        internal static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of scans: ähnelt.
        /// </summary>
        internal static string NumberOfScansLabel {
            get {
                return ResourceManager.GetString("NumberOfScansLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OCR ähnelt.
        /// </summary>
        internal static string Ocr {
            get {
                return ResourceManager.GetString("Ocr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OCR Download ähnelt.
        /// </summary>
        internal static string OcrDownloadFormTitle {
            get {
                return ResourceManager.GetString("OcrDownloadFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Using OCR requires you to download each language you want to scan. ähnelt.
        /// </summary>
        internal static string OcrDownloadSummaryText {
            get {
                return ResourceManager.GetString("OcrDownloadSummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OCR language: ähnelt.
        /// </summary>
        internal static string OcrLanguageLabel {
            get {
                return ResourceManager.GetString("OcrLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OCR mode: ähnelt.
        /// </summary>
        internal static string OcrModeLabel {
            get {
                return ResourceManager.GetString("OcrModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select one or more languages: ähnelt.
        /// </summary>
        internal static string OcrSelectLanguageLabel {
            get {
                return ResourceManager.GetString("OcrSelectLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OCR Setup ähnelt.
        /// </summary>
        internal static string OcrSetupFormTitle {
            get {
                return ResourceManager.GetString("OcrSetupFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset width based on alignment (WIA) ähnelt.
        /// </summary>
        internal static string OffsetWidth {
            get {
                return ResourceManager.GetString("OffsetWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One file per page ähnelt.
        /// </summary>
        internal static string OneFilePerPage {
            get {
                return ResourceManager.GetString("OneFilePerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One file per scan ähnelt.
        /// </summary>
        internal static string OneFilePerScan {
            get {
                return ResourceManager.GetString("OneFilePerScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Folder ähnelt.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output ähnelt.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Owner Password: ähnelt.
        /// </summary>
        internal static string OwnerPasswordLabel {
            get {
                return ResourceManager.GetString("OwnerPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Page Size ähnelt.
        /// </summary>
        internal static string PageSizeFormTitle {
            get {
                return ResourceManager.GetString("PageSizeFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page size: ähnelt.
        /// </summary>
        internal static string PageSizeLabel {
            get {
                return ResourceManager.GetString("PageSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paper source: ähnelt.
        /// </summary>
        internal static string PaperSourceLabel {
            get {
                return ResourceManager.GetString("PaperSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste ähnelt.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string PdfPasswordFormTitle {
            get {
                return ResourceManager.GetString("PdfPasswordFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF Settings ähnelt.
        /// </summary>
        internal static string PdfSettings {
            get {
                return ResourceManager.GetString("PdfSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF Settings ähnelt.
        /// </summary>
        internal static string PdfSettingsFormTitle {
            get {
                return ResourceManager.GetString("PdfSettingsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placeholders ähnelt.
        /// </summary>
        internal static string Placeholders {
            get {
                return ResourceManager.GetString("Placeholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Placeholders ähnelt.
        /// </summary>
        internal static string PlaceholdersFormTitle {
            get {
                return ResourceManager.GetString("PlaceholdersFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Post-processing ähnelt.
        /// </summary>
        internal static string PostProcessing {
            get {
                return ResourceManager.GetString("PostProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press Start when ready. ähnelt.
        /// </summary>
        internal static string PressStartWhenReady {
            get {
                return ResourceManager.GetString("PressStartWhenReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview ähnelt.
        /// </summary>
        internal static string PreviewFormTitle {
            get {
                return ResourceManager.GetString("PreviewFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview: ähnelt.
        /// </summary>
        internal static string PreviewLabel {
            get {
                return ResourceManager.GetString("PreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous ähnelt.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile: ähnelt.
        /// </summary>
        internal static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiles ähnelt.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiles ähnelt.
        /// </summary>
        internal static string ProfilesFormTitle {
            get {
                return ResourceManager.GetString("ProfilesFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prompt for file path ähnelt.
        /// </summary>
        internal static string PromptForFilePath {
            get {
                return ResourceManager.GetString("PromptForFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provider ähnelt.
        /// </summary>
        internal static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready for scan {0}. ähnelt.
        /// </summary>
        internal static string ReadyForScan {
            get {
                return ResourceManager.GetString("ReadyForScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recover ähnelt.
        /// </summary>
        internal static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recover Scanned Images ähnelt.
        /// </summary>
        internal static string RecoverFormTitle {
            get {
                return ResourceManager.GetString("RecoverFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} image(s) scanned on {1} at {2} may not have been saved, and are recoverable. Do you want to recover them? ähnelt.
        /// </summary>
        internal static string RecoverPrompt {
            get {
                return ResourceManager.GetString("RecoverPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember these settings ähnelt.
        /// </summary>
        internal static string RememberTheseSettings {
            get {
                return ResourceManager.GetString("RememberTheseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reorder ähnelt.
        /// </summary>
        internal static string Reorder {
            get {
                return ResourceManager.GetString("Reorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resolution: ähnelt.
        /// </summary>
        internal static string ResolutionLabel {
            get {
                return ResourceManager.GetString("ResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore Defaults ähnelt.
        /// </summary>
        internal static string RestoreDefaults {
            get {
                return ResourceManager.GetString("RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reverse ähnelt.
        /// </summary>
        internal static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reverse All ähnelt.
        /// </summary>
        internal static string ReverseAll {
            get {
                return ResourceManager.GetString("ReverseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reverse Selected ähnelt.
        /// </summary>
        internal static string ReverseSelected {
            get {
                return ResourceManager.GetString("ReverseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revert ähnelt.
        /// </summary>
        internal static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotate ähnelt.
        /// </summary>
        internal static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotate Left ähnelt.
        /// </summary>
        internal static string RotateLeft {
            get {
                return ResourceManager.GetString("RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotate Right ähnelt.
        /// </summary>
        internal static string RotateRight {
            get {
                return ResourceManager.GetString("RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run in Background ähnelt.
        /// </summary>
        internal static string RunInBackground {
            get {
                return ResourceManager.GetString("RunInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically run OCR after scanning ähnelt.
        /// </summary>
        internal static string RunOcrAfterScanning {
            get {
                return ResourceManager.GetString("RunOcrAfterScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SANE Driver ähnelt.
        /// </summary>
        internal static string SaneDriver {
            get {
                return ResourceManager.GetString("SaneDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save All ähnelt.
        /// </summary>
        internal static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save All as Images ähnelt.
        /// </summary>
        internal static string SaveAllAsImages {
            get {
                return ResourceManager.GetString("SaveAllAsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save All as PDF ähnelt.
        /// </summary>
        internal static string SaveAllAsPdf {
            get {
                return ResourceManager.GetString("SaveAllAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Save&quot; button default action: ähnelt.
        /// </summary>
        internal static string SaveButtonDefaultAction {
            get {
                return ResourceManager.GetString("SaveButtonDefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Images ähnelt.
        /// </summary>
        internal static string SaveImages {
            get {
                return ResourceManager.GetString("SaveImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save PDF ähnelt.
        /// </summary>
        internal static string SavePdf {
            get {
                return ResourceManager.GetString("SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Selected ähnelt.
        /// </summary>
        internal static string SaveSelected {
            get {
                return ResourceManager.GetString("SaveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Selected as Images ähnelt.
        /// </summary>
        internal static string SaveSelectedAsImages {
            get {
                return ResourceManager.GetString("SaveSelectedAsImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Selected as PDF ähnelt.
        /// </summary>
        internal static string SaveSelectedAsPdf {
            get {
                return ResourceManager.GetString("SaveSelectedAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save to multiple files ähnelt.
        /// </summary>
        internal static string SaveToMultipleFiles {
            get {
                return ResourceManager.GetString("SaveToMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save to a single file ähnelt.
        /// </summary>
        internal static string SaveToSingleFile {
            get {
                return ResourceManager.GetString("SaveToSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale: ähnelt.
        /// </summary>
        internal static string ScaleLabel {
            get {
                return ResourceManager.GetString("ScaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale With Window ähnelt.
        /// </summary>
        internal static string ScaleWithWindow {
            get {
                return ResourceManager.GetString("ScaleWithWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan ähnelt.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Scan&quot; button default action: ähnelt.
        /// </summary>
        internal static string ScanButtonDefaultAction {
            get {
                return ResourceManager.GetString("ScanButtonDefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Scan&quot; menu changes default profile ähnelt.
        /// </summary>
        internal static string ScanChangesDefaultProfile {
            get {
                return ResourceManager.GetString("ScanChangesDefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan Configuration ähnelt.
        /// </summary>
        internal static string ScanConfig {
            get {
                return ResourceManager.GetString("ScanConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanner Sharing ähnelt.
        /// </summary>
        internal static string ScannerSharing {
            get {
                return ResourceManager.GetString("ScannerSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanner Sharing ähnelt.
        /// </summary>
        internal static string ScannerSharingFormTitle {
            get {
                return ResourceManager.GetString("ScannerSharingFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shared scanners can be used from other computers on the local network by selecting &quot;ESCL Driver&quot; in the other computer&apos;s NAPS2 profile settings. ähnelt.
        /// </summary>
        internal static string ScannerSharingIntro {
            get {
                return ResourceManager.GetString("ScannerSharingIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Second (00-59) ähnelt.
        /// </summary>
        internal static string Second2Digit {
            get {
                return ResourceManager.GetString("Second2Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select All ähnelt.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Source ähnelt.
        /// </summary>
        internal static string SelectSource {
            get {
                return ResourceManager.GetString("SelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Separate files by Patch-T ähnelt.
        /// </summary>
        internal static string SeparateByPatchT {
            get {
                return ResourceManager.GetString("SeparateByPatchT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Default ähnelt.
        /// </summary>
        internal static string SetDefault {
            get {
                return ResourceManager.GetString("SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string SettingsFormTitle {
            get {
                return ResourceManager.GetString("SettingsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Share ähnelt.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Share even when NAPS2 is closed ähnelt.
        /// </summary>
        internal static string ShareAsService {
            get {
                return ResourceManager.GetString("ShareAsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shared Scanner Settings ähnelt.
        /// </summary>
        internal static string SharedDeviceFormTitle {
            get {
                return ResourceManager.GetString("SharedDeviceFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sharpen ähnelt.
        /// </summary>
        internal static string Sharpen {
            get {
                return ResourceManager.GetString("Sharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show ähnelt.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show page numbers ähnelt.
        /// </summary>
        internal static string ShowPageNumbers {
            get {
                return ResourceManager.GetString("ShowPageNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show &quot;Profiles&quot; toolbar ähnelt.
        /// </summary>
        internal static string ShowProfilesToolbar {
            get {
                return ResourceManager.GetString("ShowProfilesToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only allow a single NAPS2 instance ähnelt.
        /// </summary>
        internal static string SingleInstanceDesc {
            get {
                return ResourceManager.GetString("SingleInstanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single page files ähnelt.
        /// </summary>
        internal static string SinglePageFiles {
            get {
                return ResourceManager.GetString("SinglePageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single scan ähnelt.
        /// </summary>
        internal static string SingleScan {
            get {
                return ResourceManager.GetString("SingleScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skip save prompt ähnelt.
        /// </summary>
        internal static string SkipSavePrompt {
            get {
                return ResourceManager.GetString("SkipSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Squeeze ähnelt.
        /// </summary>
        internal static string Squeeze {
            get {
                return ResourceManager.GetString("Squeeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        internal static string SqueezeAll {
            get {
                return ResourceManager.GetString("SqueezeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        internal static string SqueezeSelected {
            get {
                return ResourceManager.GetString("SqueezeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQZ Settings ähnelt.
        /// </summary>
        internal static string SqueezeSettings {
            get {
                return ResourceManager.GetString("SqueezeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Squeeze Config ähnelt.
        /// </summary>
        internal static string SqueezeSettingsForm {
            get {
                return ResourceManager.GetString("SqueezeSettingsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Document Class ähnelt.
        /// </summary>
        internal static string SQZClassID {
            get {
                return ResourceManager.GetString("SQZClassID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client ähnelt.
        /// </summary>
        internal static string SQZClient {
            get {
                return ResourceManager.GetString("SQZClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string SQZPassword {
            get {
                return ResourceManager.GetString("SQZPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server URL ähnelt.
        /// </summary>
        internal static string SQZServerURL {
            get {
                return ResourceManager.GetString("SQZServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        internal static string SQZUserName {
            get {
                return ResourceManager.GetString("SQZUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stretch to page size ähnelt.
        /// </summary>
        internal static string StretchToPageSize {
            get {
                return ResourceManager.GetString("StretchToPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subject: ähnelt.
        /// </summary>
        internal static string SubjectLabel {
            get {
                return ResourceManager.GetString("SubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Technical Details ähnelt.
        /// </summary>
        internal static string TechnicalDetails {
            get {
                return ResourceManager.GetString("TechnicalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tiff Options ähnelt.
        /// </summary>
        internal static string TiffOptions {
            get {
                return ResourceManager.GetString("TiffOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time between scans (seconds): ähnelt.
        /// </summary>
        internal static string TimeBetweenScansLabel {
            get {
                return ResourceManager.GetString("TimeBetweenScansLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title: ähnelt.
        /// </summary>
        internal static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TWAIN Driver ähnelt.
        /// </summary>
        internal static string TwainDriver {
            get {
                return ResourceManager.GetString("TwainDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Twain Implementation: ähnelt.
        /// </summary>
        internal static string TwainImplLabel {
            get {
                return ResourceManager.GetString("TwainImplLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use native UI ähnelt.
        /// </summary>
        internal static string UseNativeUi {
            get {
                return ResourceManager.GetString("UseNativeUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use predefined settings ähnelt.
        /// </summary>
        internal static string UsePredefinedSettings {
            get {
                return ResourceManager.GetString("UsePredefinedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Password: ähnelt.
        /// </summary>
        internal static string UserPasswordLabel {
            get {
                return ResourceManager.GetString("UserPasswordLabel", resourceCulture);
            }
        }
        internal static string UploadAllToSqueeze
        {
            get
            {
                return ResourceManager.GetString("UploadAllToSqueeze", resourceCulture);
            }
        }
        internal static string UploadSelectedToSqueeze
        {
            get
            {
                return ResourceManager.GetString("UploadSelectedToSqueeze", resourceCulture);
            }
        }
        internal static string UploadToSqueeze
        {
            get
            {
                return ResourceManager.GetString("UploadToSqueeze", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for authorization... ähnelt.
        /// </summary>
        internal static string WaitingForAuthorization {
            get {
                return ResourceManager.GetString("WaitingForAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for TWAIN to complete... ähnelt.
        /// </summary>
        internal static string WaitingForTwain {
            get {
                return ResourceManager.GetString("WaitingForTwain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die White Threshold ähnelt.
        /// </summary>
        internal static string WhiteThreshold {
            get {
                return ResourceManager.GetString("WhiteThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WIA Driver ähnelt.
        /// </summary>
        internal static string WiaDriver {
            get {
                return ResourceManager.GetString("WiaDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wia Version: ähnelt.
        /// </summary>
        internal static string WiaVersionLabel {
            get {
                return ResourceManager.GetString("WiaVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of {1} ähnelt.
        /// </summary>
        internal static string XOfY {
            get {
                return ResourceManager.GetString("XOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year (00-99) ähnelt.
        /// </summary>
        internal static string Year2Digit {
            get {
                return ResourceManager.GetString("Year2Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        internal static string Year4Digit {
            get {
                return ResourceManager.GetString("Year4Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom ähnelt.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom Actual ähnelt.
        /// </summary>
        internal static string ZoomActual {
            get {
                return ResourceManager.GetString("ZoomActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom In ähnelt.
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoom Out ähnelt.
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
