//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.ConsoleResources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.ConsoleResources.ConsoleResources", typeof(ConsoleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attaching {0}... ähnelt.
        /// </summary>
        internal static string Attaching {
            get {
                return ResourceManager.GetString("Attaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attaching the previously exported PDF... ähnelt.
        /// </summary>
        internal static string AttachingExportedPDF {
            get {
                return ResourceManager.GetString("AttachingExportedPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto save is not enabled for the specified profile. ähnelt.
        /// </summary>
        internal static string AutoSaveNotEnabled {
            get {
                return ResourceManager.GetString("AutoSaveNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto saving... ähnelt.
        /// </summary>
        internal static string AutoSaving {
            get {
                return ResourceManager.GetString("AutoSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginning scan... ähnelt.
        /// </summary>
        internal static string BeginningScan {
            get {
                return ResourceManager.GetString("BeginningScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified component is already installed. ähnelt.
        /// </summary>
        internal static string ComponentAlreadyInstalled {
            get {
                return ResourceManager.GetString("ComponentAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An additional component is needed to perform this operation. Run &quot;NAPS2.Console --install {0}&quot; to install it. ähnelt.
        /// </summary>
        internal static string ComponentNeeded {
            get {
                return ResourceManager.GetString("ComponentNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified component to install is not available. Check your spelling. ähnelt.
        /// </summary>
        internal static string ComponentNotAvailable {
            get {
                return ResourceManager.GetString("ComponentNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The encryption configuration file could not be loaded. ähnelt.
        /// </summary>
        internal static string CouldntLoadEncryptionConfig {
            get {
                return ResourceManager.GetString("CouldntLoadEncryptionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You don&apos;t have permission to save files at this location. ähnelt.
        /// </summary>
        internal static string DontHavePermission {
            get {
                return ResourceManager.GetString("DontHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emailing... ähnelt.
        /// </summary>
        internal static string Emailing {
            get {
                return ResourceManager.GetString("Emailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email not sent. ähnelt.
        /// </summary>
        internal static string EmailNotSent {
            get {
                return ResourceManager.GetString("EmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email successfully sent. ähnelt.
        /// </summary>
        internal static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred when trying to delete a temporary directory. ähnelt.
        /// </summary>
        internal static string ErrorDeletingTempDir {
            get {
                return ResourceManager.GetString("ErrorDeletingTempDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error importing file. Path: {0} ähnelt.
        /// </summary>
        internal static string ErrorImporting {
            get {
                return ResourceManager.GetString("ErrorImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred when trying to save the file. ähnelt.
        /// </summary>
        internal static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exporting... ähnelt.
        /// </summary>
        internal static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exporting image {0} of {1}... ähnelt.
        /// </summary>
        internal static string ExportingImage {
            get {
                return ResourceManager.GetString("ExportingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exporting images for use as an attachment... ähnelt.
        /// </summary>
        internal static string ExportingImagesToAttach {
            get {
                return ResourceManager.GetString("ExportingImagesToAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exporting page {0} of {1}. ähnelt.
        /// </summary>
        internal static string ExportingPage {
            get {
                return ResourceManager.GetString("ExportingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exporting PDF for use as an attachment... ähnelt.
        /// </summary>
        internal static string ExportingPDFToAttach {
            get {
                return ResourceManager.GetString("ExportingPDFToAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File already exists. Use --force to overwrite. Path: {0} ähnelt.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finished saving images to {0} ähnelt.
        /// </summary>
        internal static string FinishedSavingImages {
            get {
                return ResourceManager.GetString("FinishedSavingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imported file {0} of {1}. ähnelt.
        /// </summary>
        internal static string ImportedFile {
            get {
                return ResourceManager.GetString("ImportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file could not be imported because it requires a password.
        ///Use the &quot;--importpassword&quot; option. ähnelt.
        /// </summary>
        internal static string ImportErrorNoPassword {
            get {
                return ResourceManager.GetString("ImportErrorNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file could not be imported because the provided password was incorrect. ähnelt.
        /// </summary>
        internal static string ImportErrorWrongPassword {
            get {
                return ResourceManager.GetString("ImportErrorWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importing... ähnelt.
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installing {0}... ähnelt.
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NAPS2 ähnelt.
        /// </summary>
        internal static string NAPS2 {
            get {
                return ResourceManager.GetString("NAPS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No scanned pages to email. ähnelt.
        /// </summary>
        internal static string NoPagesToEmail {
            get {
                return ResourceManager.GetString("NoPagesToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No scanned pages to export. ähnelt.
        /// </summary>
        internal static string NoPagesToExport {
            get {
                return ResourceManager.GetString("NoPagesToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At least one of the -o/--output, -e/--email, or -a/--autosave options must be specified. ähnelt.
        /// </summary>
        internal static string OutputOrEmailRequired {
            get {
                return ResourceManager.GetString("OutputOrEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At least one of the -o/--output or -e/--email options must be specified if -i/--import is specified. Import does not work with -a/--autosave. ähnelt.
        /// </summary>
        internal static string OutputOrEmailRequiredForImport {
            get {
                return ResourceManager.GetString("OutputOrEmailRequiredForImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwriting: {0} ähnelt.
        /// </summary>
        internal static string Overwriting {
            get {
                return ResourceManager.GetString("Overwriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} page(s) scanned. ähnelt.
        /// </summary>
        internal static string PagesScanned {
            get {
                return ResourceManager.GetString("PagesScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified profile is unavailable or ambiguous.
        ///Use the --profile option to specify a profile by name. ähnelt.
        /// </summary>
        internal static string ProfileUnavailableOrAmbiguous {
            get {
                return ResourceManager.GetString("ProfileUnavailableOrAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanned Image ähnelt.
        /// </summary>
        internal static string ScannedImage {
            get {
                return ResourceManager.GetString("ScannedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scanned page {0}. ähnelt.
        /// </summary>
        internal static string ScannedPage {
            get {
                return ResourceManager.GetString("ScannedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sending email... ähnelt.
        /// </summary>
        internal static string SendingEmail {
            get {
                return ResourceManager.GetString("SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting scan {0} of {1}... ähnelt.
        /// </summary>
        internal static string StartingScan {
            get {
                return ResourceManager.GetString("StartingScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully saved PDF file to {0} ähnelt.
        /// </summary>
        internal static string SuccessfullySavedPdf {
            get {
                return ResourceManager.GetString("SuccessfullySavedPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected error occurred. ähnelt.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting {0}ms... ähnelt.
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
    }
}
